# Generated by Django 6.0.6 on 2026-06-21 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_de_sono', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consumo_de_agua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('patologias', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('nivel_estresse', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Adipometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricipital', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supra_iliaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axilar_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adipometria', to='pacientes.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Circunferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdome', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circunferencias', to='pacientes.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='HabitosAlimentares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_da_manha', models.BooleanField(default=True)),
                ('almoco', models.BooleanField(default=True)),
                ('jantar', models.BooleanField(default=True)),
                ('lanches', models.BooleanField(default=False)),
                ('consumo_alcool', models.BooleanField(default=False)),
                ('fumante', models.BooleanField(default=False)),
                ('frequencia_fast_food', models.CharField(blank=True, max_length=50, null=True)),
                ('alimentos_preferidos', models.TextField(blank=True, null=True)),
                ('alimentos_rejeitados', models.TextField(blank=True, null=True)),
                ('suplementacao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('quantidade_refeicoes', models.IntegerField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos_alimentares', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densidade_corporal', models.FloatField(blank=True, null=True)),
                ('percentual_gordura', models.FloatField(blank=True, null=True)),
                ('massa_magra', models.FloatField(blank=True, null=True)),
                ('massa_gorda', models.FloatField(blank=True, null=True)),
                ('tmb', models.FloatField(blank=True, null=True)),
                ('get', models.FloatField(blank=True, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='pacientes.avaliacao')),
            ],
        ),
    ]
